[package]
name = "rope_bridge"
version = "0.1.0"
edition = "2021"
homepage = "https://adventofcode.com/2022/day/9"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared_lib = { path = "../../shared_lib" }
